name: ARM64 build

on:
  # run every day of the week at 06:00
  schedule:
    - cron: 0 6 * * *

jobs:
  build-arm64-docker:
    name: Build for ARM64 on Docker
    runs-on: ubuntu-18.04
    steps:
    - name: Install docker
      run: |
        # bug in ubuntu, conflicts with docker.io
        sudo apt-get update
        sudo apt-get remove --purge -y moby-engine moby-cli
        sudo apt-get install -y qemu-system docker.io

    - name: Setup ARM64 build env
      run: |
        uname -a
        sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
        uname -a

    - uses: actions/checkout@v1

    - name: ARM64 build
      run: |
        sudo docker build -t htm-arm64-docker --build-arg arch=arm64 .
        uname -a

